const g = require("../");

g.addV("person")
  .property("name", "bob")
  .as("bob")
  .addV("person")
  .property("name", "stephen")
  .as("stephen")
  .addV("company")
  .property("name", "Blueprints, Inc")
  .as("blueprints")
  .addV("company")
  .property("name", "Rexster, LLC")
  .as("rexster")
  .addV("job")
  .property("name", "job1")
  .as("blueprintsJob1")
  .addV("job")
  .property("name", "job2")
  .as("blueprintsJob2")
  .addV("job")
  .property("name", "job3")
  .as("blueprintsJob3")
  .addV("job")
  .property("name", "job4")
  .as("rexsterJob1")
  .addV("application")
  .property("name", "application1")
  .as("appBob1")
  .addV("application")
  .property("name", "application2")
  .as("appBob2")
  .addV("application")
  .property("name", "application3")
  .as("appStephen1")
  .addV("application")
  .property("name", "application4")
  .as("appStephen2")
  .addE("completes")
  .from_("bob")
  .to("appBob1")
  .addE("completes")
  .from_("bob")
  .to("appBob2")
  .addE("completes")
  .from_("stephen")
  .to("appStephen1")
  .addE("completes")
  .from_("stephen")
  .to("appStephen2")
  .addE("appliesTo")
  .from_("appBob1")
  .to("blueprintsJob1")
  .addE("appliesTo")
  .from_("appBob2")
  .to("blueprintsJob2")
  .addE("appliesTo")
  .from_("appStephen1")
  .to("rexsterJob1")
  .addE("appliesTo")
  .from_("appStephen2")
  .to("blueprintsJob3")
  .addE("created")
  .from_("blueprints")
  .to("blueprintsJob1")
  .property("creationDate", "12/20/2015")
  .addE("created")
  .from_("blueprints")
  .to("blueprintsJob2")
  .property("creationDate", "12/15/2015")
  .addE("created")
  .from_("blueprints")
  .to("blueprintsJob3")
  .property("creationDate", "12/16/2015")
  .addE("created")
  .from_("rexster")
  .to("rexsterJob1")
  .property("creationDate", "12/18/2015")
  .iterate();
